### ISSUE TITLE
Merge Entropy Source (ES) instruction & guidance into specification.

### ISSUE THREAD

**Issue by ben-marshall** [scarv/riscv-crypto#14]
Current ES proposal has been developed in [doc/supp/pollentropy.adoc](https://github.com/scarv/riscv-crypto/blob/master/doc/supp/pollentropy.adoc).

This is now stable enough to be moved into the draft spec.

- [ ] Instruction / ISA level description section.
- [ ] Appendix / supplementary section containing guidance for implementers.

**Comment by mjosaarinen** [comment]
In next release branch:
:ballot_box_with_check:  Instruction / ISA level description section.
:ballot_box_with_check:  Appendix / supplementary section containing guidance for implementers.

There's also a paper on eprint with closely related content now: https://eprint.iacr.org/2020/866
Markku-Juhani O. Saarinen and G. Richard Newell and Ben Marshall:
*"Building a Modern TRNG: An Entropy Source Interface for RISC-V"*
Cryptology ePrint Archive: Report 2020/866.
